AWSTemplateFormatVersion: '2010-09-09'
Description: Stack que descreve os recursos de persistencia de dados relacionados à User API

Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-users'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: pk
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: userIdIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
